export const states = [
    { id: 1, code: 1, name: "JAMMU AND KASHMIR" },
    { id: 2, code: 2, name: "HIMACHAL PRADESH" },
    { id: 3, code: 3, name: "PUNJAB" },
    { id: 4, code: 4, name: "CHANDIGARH" },
    { id: 5, code: 5, name: "UTTARAKHAND" },
    { id: 6, code: 6, name: "HARYANA" },
    { id: 7, code: 7, name: "DELHI" },
    { id: 8, code: 8, name: "RAJASTHAN" },
    { id: 9, code: 9, name: "UTTAR PRADESH" },
    { id: 10, code: 10, name: "BIHAR" },
    { id: 11, code: 11, name: "SIKKIM" },
    { id: 12, code: 12, name: "ARUNACHAL PRADESH" },
    { id: 13, code: 13, name: "NAGALAND" },
    { id: 14, code: 14, name: "MANIPUR" },
    { id: 15, code: 15, name: "MIZORAM" },
    { id: 16, code: 16, name: "TRIPURA" },
    { id: 17, code: 17, name: "MEGHALAYA" },
    { id: 18, code: 18, name: "ASSAM" },
    { id: 19, code: 19, name: "WEST BENGAL" },
    { id: 20, code: 20, name: "JHARKHAND" },
    { id: 21, code: 21, name: "ORISSA" },
    { id: 22, code: 22, name: "CHHATTISGARH" },
    { id: 23, code: 23, name: "MADHYA PRADESH" },
    { id: 24, code: 24, name: "GUJARAT" },
    { id: 25, code: 25, name: "DAMAN AND DIU" },
    { id: 26, code: 26, name: "DADAR AND NAGAR HAVELI" },
    { id: 27, code: 27, name: "MAHARASTRA" },
    { id: 28, code: 29, name: "KARNATAKA" },
    { id: 29, code: 30, name: "GOA" },
    { id: 30, code: 31, name: "LAKSHADWEEP" },
    { id: 31, code: 32, name: "KERALA" },
    { id: 32, code: 33, name: "TAMIL NADU" },
    { id: 33, code: 34, name: "PUDUCHERRY" },
    { id: 34, code: 35, name: "ANDAMAN AND NICOBAR" },
    { id: 35, code: 36, name: "TELANGANA" },
    { id: 36, code: 37, name: "ANDHRA PRADESH" },
    { id: 37, code: 97, name: "OTHER TERRITORY" },
    { id: 38, code: 96, name: "OTHER COUNTRY" }
  ];
  